<?php

return array(
    "BIR MOURAD RAIS",
    "GARIDI",
    "RV-20000",
    "BOUDOUAOU",
    "BADJARAH AGENCE",
    "ROUISSEAU",
    "REGHAIA STEP",
    "CHERAGA",
    "HOUSSEIN DEY",
    "EL HARRACH PARC",
    "BABA HASSEN",
    "desalement ain-beniane",
    "DIDOUCHE MOURAD",
    "DELY IBRAHIM",
    "Bordj-El-Kiffan",
    "BEB EL OUED",
    "R-AGENCE-DOUERA",
    "SW-CATO-PABX",
    "El achour",
    "ZERALDA Agence",
    "R-CAISSE-AINTAYA",
    "Chaigh",
    "Agence tipaza",
    "Sidi yahia tipaza",
    "Sidi moussa ",
    "CPK alger centre ",
    "Step zeralda",
    "Agence menaceur",
    "APPREVAL",
    "AIN-NAADJA",
    "GUE DE CONTANTINE",
    "Badjarah-assainissement",
    "dd-DAR-EL-BEIDA",
    "CHERARBA DAL",
    "REGHAIA",
    "TESSALA EL MERDJA SP1",
    "SEBALA",
    "agence BOUZAREAH",
    "DRARIA  CENTRE",
    "agence BIRTOUTA",
    "BIRTOUTA VILLE",
    "agence sidi-abdellah",
    "BAB-EZZOUAR",
    "PRISE D'EAU",
    "agence DOUERA",
    "BENI MESSOUS STEP",
    "MAZAFRAN SAA",
    "BABA HASSEN Assainissement",
    "BARAKI AGENCE",
    "STAOUALI DISTRIBUTION",
    "APPREVAL 2",
    "BARAKI STEP",
    "agence TIKAROUCHINE",
    "agence BOUMAATI",
    "agence ROUIBA",
    "Saada",
    "TAKSEBT",
    "STEP-BEZ",
    "Centre-birtouta-ass",
    "R-FOUKA",
    "AGENCE-DOUAOUDA",
    "CAISSE-MENACEUR",
    "CHERCHEL AGENCE",
    "Centre Cherchel DD",
    "R-CENTRE-TRAITEMENT-SIDIAMER",
    "R-CAISSE-SIDIAMER",
    "dd-BOUSMAIL",
    "TIPAZA PORT",
    "Agence Tipaza (laboratoire)",
    "AGENCE-CHAIBA",
    "agence KOLEA",
    "centre hajout / agence",
    "caisse-ahmeur-ain",
    "SIGE-ONA-CHINOUA",
    "Centre d'Assinnissement Tipaza",
    "HADJOUT-ASSAI",
    "Centre d'Assinnissement Cherchel",
    "CENTREASSI-KOLEA",
    "Bouchaoui",
    "step hajout",
    "Château-d'eau beraki ",
    "agence BENTALHA",
    "CAISSE-GOURAYA",
    "FRAISVALLONS",
    "NV-AGENCE-BOUSMAIL",
    "RV-2000",
    "DD-Birkhadem",
    "Magasin-Hydra",
    "agence ainbenian",
    "damous",
    "nv-c-p-fouka",
    "ROUIBA CENTRE",
    "DD-MOHAMADIA",
    "dtx haouch-felit",
    "STAOUALI STEP",
    "sp4 ain beniane",
    "KOLEA STEP",

);
